### ISSUE TITLE
Remove Domain assertions that will cause unintended inferencing errors.

### ISSUE THREAD

**Issue by rhohimer** [ucoProject/UCO#104] opened 2019-07-02 22:32 UTC
As with some ontologies written without the original intent to use an inference engine, Domain assertions were used to extensively.

Comb through the ontology and remove any non-essential domain settings

**Comment by sbarnum** [comment] 2019-07-03 13:43
I agree with a desire to rectify the potential unintended impacts on inferencing caused by properties with multiple domains declared.
That being said, we can only do this sort of domain removal if at the same time we find a different way to assert all of the class<->property relationships in the ontology. We definitely cannot just remove the domains as that would lose all of the structure of the ontology and leave us with just a vocabulary of terms. Luckily, the cardinality restrictions for each property on each class gives us the structural relationships for set cardinalities, minCardinalities & maxCardinalities but they do not provide structural relationships for cardinality of 0..n.
We MUST find a solution to this issue before we can remove Domains.

**Comment by rhohimer** [comment] 2019-07-05 21:52
Event, GeoLocationEntry, GeoLocationLog, GeoLocationTrack, Note ..... PhoneCalls?
![image](https://user-images.githubusercontent.com/9854293/60746620-8cbfb300-9f34-11e9-9bac-95df7f52d01a.png)

**Comment by rhohimer** [comment] 2019-07-10 16:22
It is not that setting a domain on a property is bad practice, to the contrary, it is good practice. However, you have to be careful when setting these axioms.  An example from UCO is the observable:domain ObjectProperty…

Anything that asserts it has an observable:domain will be typed by an inference engine (reasoner) as a WindowsComputerSpecification and a BrowserCookie. Is this REALLY the intent? Probably not, but the computer will consider the axioms as the formal logical truth. 

![image](https://user-images.githubusercontent.com/9854293/60985511-7b8af380-a2f2-11e9-8e36-edac16876019.png)

  
If the true intent is to type anything with a observable:domain as a BrowserCookie and WindowsCompterSpecification this seems a bit weird. Don't most CyberItem objects have a domain they reside in?

**Comment by sbarnum** [comment] 2020-03-12 15:59
Addressed in commit c36115b93e7f1d3f819b4424f481ba089d7340ce

**Comment by sbarnum** [comment] 2020-06-01 21:35
Fixed in https://github.com/ucoProject/UCO/releases/tag/0.4.0

**Closed by sbarnum** 2020-06-01 21:35 UTC
Labels: committed, v0.4.0
